# Uncomment this line to define a global platform for your project
# platform :ios, “7.0”

inhibit_all_warnings!

target "WebRTCOfficeDemo" do

platform :ios, '9.0'
  pod 'GoogleWebRTC'
  pod 'CocoaAsyncSocket'
  pod 'SocketRocket'
end

